# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "phyVIP2"
BBFILE_PATTERN_phyVIP2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_phyVIP2 = "30"
LAYERSERIES_COMPAT_phyVIP2 = "scarthgap walnascar"
LAYERDEPENDS_phyVIP2 = "phytec ampliphy"
